# This workflow will launch at 00:00 every Sunday
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Set Git author
        run: |
          git config --global user.name "scala-steward[bot]"
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          author-name: 'scala-steward[bot]'
          github-token: ${{ secrets.SCALA_STEWARD_TOKEN }}
